### ISSUE TITLE
itera.may-be.gay

### ISSUE THREAD

**Issue by IteraRuiner** [may-be-gay/register#10]
URL of Website: https://iteraruiner.netlify.app

Short Description: Personal Website of a Software Developer.

Selected Subdomain: itera.may-be.gay

CNAME Record:

Name it `itera` and point it to iteraruiner.netlify.app.

**Comment by rayhanadev** [comment]
Hiya! You can actually create a pull request to this repository to setup your domain :).

The process is detailed [here](https://github.com/may-be-gay/register#new-method-recommended). Look forward to your PR! 👋

**Comment by IteraRuiner** [comment]
thank you! I'll do it right now.
